version: '3.9'

services:
  db:
    image: postgres:15
    container_name: ar_db
    restart: always
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: ar_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  backend:
    build: .
    container_name: arbackend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=user;Password=pass;Database=ar_db

volumes:
  pgdata: